sudo: required
services:
  - docker
  
before_install:
  - docker build -t bmalecky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bmalecky/react-test npm test

after_success:
  - docker build -t bmaleckysandbox/multi-client ./client
  - docker build -t bmaleckysandbox/multi-nginx ./nginx
  - docker build -t bmaleckysandbox/multi-server ./server
  - docker build -t bmaleckysandbox/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub    
  - docker push bmaleckysandbox/multi-client
  - docker push bmaleckysandbox/multi-nginx
  - docker push bmaleckysandbox/multi-server
  - docker push bmaleckysandbox/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-671719585280
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  